CREATE OR REPLACE WAREHOUSE PIXAR_WH
WITH WAREHOUSE_SIZE = 'X-SMALL'
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE DATABASE PIXAR_DB;

CREATE OR REPLACE SCHEMA PIXAR_DB.RAW;
CREATE OR REPLACE SCHEMA PIXAR_DB.STAGING;
CREATE OR REPLACE SCHEMA PIXAR_DB.MARTS;

USE DATABASE PIXAR_DB;
USE WAREHOUSE PIXAR_WH;

CREATE OR REPLACE ROLE PIXAR_ROLE;

GRANT OWNERSHIP ON WAREHOUSE PIXAR_WH TO PIXAR_ROLE;
GRANT OWNERSHIP ON DATABASE PIXAR_DB TO PIXAR_ROLE;
GRANT USAGE ON WAREHOUSE PIXAR_WH TO ROLE PIXAR_ROLE;
GRANT USAGE ON DATABASE PIXAR_DB TO ROLE PIXAR_ROLE;
GRANT ALL ON SCHEMA PIXAR_DB.RAW TO ROLE PIXAR_ROLE;
GRANT ALL ON SCHEMA PIXAR_DB.STAGING TO ROLE PIXAR_ROLE;
GRANT ALL ON SCHEMA PIXAR_DB.MARTS TO ROLE PIXAR_ROLE;

GRANT ROLE PIXAR_ROLE TO USER SUNDAR139;

ALTER USER SUNDAR139 SET DEFAULT_ROLE = PIXAR_ROLE;
ALTER USER SUNDAR139 SET DEFAULT_WAREHOUSE = PIXAR_WH;

CREATE OR REPLACE FILE FORMAT PIXAR_DB.RAW.CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
RECORD_DELIMITER = '\n'
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE
ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
ESCAPE = 'NONE'
ESCAPE_UNENCLOSED_FIELD = '\134'
DATE_FORMAT = 'AUTO'
TIMESTAMP_FORMAT = 'AUTO'
NULL_IF = ('NULL', 'null', '', 'N/A', 'n/a', 'NA');

CREATE OR REPLACE STAGE PIXAR_DB.RAW.PIXAR_STAGE
FILE_FORMAT = PIXAR_DB.RAW.CSV_FORMAT;

CREATE OR REPLACE TABLE PIXAR_DB.RAW.PIXAR_FILMS (
    number INT,
    film STRING,
    release_date STRING,
    run_time INT,
    film_rating STRING,
    plot STRING
);

CREATE OR REPLACE TABLE PIXAR_DB.RAW.PIXAR_PEOPLE (
    film STRING,
    role_type STRING,
    name STRING
);

CREATE OR REPLACE TABLE PIXAR_DB.RAW.GENRE (
    film STRING,
    category STRING,
    value STRING
);

CREATE OR REPLACE TABLE PIXAR_DB.RAW.BOX_OFFICE (
    film STRING,
    budget FLOAT,
    box_office_us_canada INT,
    box_office_other INT,
    box_office_worldwide INT
);

CREATE OR REPLACE TABLE PIXAR_DB.RAW.PUBLIC_RESPONSE (
    film STRING,
    rotten_tomatoes_score INT,
    rotten_tomatoes_counts INT,
    metacritic_score INT,
    metacritic_counts INT,
    cinema_score STRING,
    imdb_score FLOAT,
    imdb_counts INT
);

CREATE OR REPLACE TABLE PIXAR_DB.RAW.ACADEMY (
    film STRING,
    award_type STRING,
    status STRING
);

CREATE OR REPLACE TABLE PIXAR_DB.RAW.PIXAR_DATA_DICTIONARY (
    table_name STRING,
    field STRING,
    description STRING
);


COPY INTO PIXAR_DB.RAW.PIXAR_FILMS
FROM @PIXAR_DB.RAW.PIXAR_STAGE/pixar_films.csv;

COPY INTO PIXAR_DB.RAW.PIXAR_PEOPLE
FROM @PIXAR_DB.RAW.PIXAR_STAGE/pixar_people.csv;

COPY INTO PIXAR_DB.RAW.GENRE
FROM @PIXAR_DB.RAW.PIXAR_STAGE/genre.csv;

COPY INTO PIXAR_DB.RAW.BOX_OFFICE
FROM @PIXAR_DB.RAW.PIXAR_STAGE/box_office.csv;

COPY INTO PIXAR_DB.RAW.PUBLIC_RESPONSE
FROM @PIXAR_DB.RAW.PIXAR_STAGE/public_response.csv;

COPY INTO PIXAR_DB.RAW.ACADEMY
FROM @PIXAR_DB.RAW.PIXAR_STAGE/academy.csv;

COPY INTO PIXAR_DB.RAW.PIXAR_DATA_DICTIONARY
FROM @PIXAR_DB.RAW.PIXAR_STAGE/pixar_data_dictionary.csv;

USE DATABASE PIXAR_DB;

SHOW SCHEMAS;

USE SCHEMA STAGING;
SELECT COUNT(*) FROM STG_PIXAR_FILMS;
SELECT COUNT(*) FROM STG_PIXAR_PEOPLE;
SELECT COUNT(*) FROM STG_BOX_OFFICE;

USE SCHEMA MARTS;
SELECT COUNT(*) FROM FACT_FILM_PERFORMANCE;
SELECT COUNT(*) FROM DIM_FILMS;

SELECT film_title, box_office_worldwide, rotten_tomatoes_score 
FROM FACT_FILM_PERFORMANCE 
LIMIT 5;

SELECT COUNT(*) FROM RPT_FINANCIAL_ANALYSIS;
SELECT COUNT(*) FROM RPT_CRITICAL_ANALYSIS;
SELECT COUNT(*) FROM RPT_GENRE_PERFORMANCE;
SELECT COUNT(*) FROM RPT_PEOPLE_ANALYSIS;

SELECT 
    film_title, 
    market_tier, 
    financial_performance_category,
    vs_decade_performance
FROM RPT_FINANCIAL_ANALYSIS
WHERE market_tier = 'Billion Dollar Club';

USE ROLE PIXAR_ROLE;
USE DATABASE PIXAR_DB;
USE SCHEMA MARTS;
SHOW TABLES;

SELECT COUNT(*) FROM FACT_FILM_PERFORMANCE;
SELECT COUNT(*) FROM DIM_FILMS;

SELECT 
    COUNT(*) as total_films,
    ROUND(AVG(box_office_worldwide), 0) as avg_box_office,
    ROUND(AVG(roi_ratio), 2) as avg_roi,
    ROUND(AVG(rotten_tomatoes_score), 1) as avg_rt_score,
    SUM(box_office_worldwide) as total_revenue
FROM FACT_FILM_PERFORMANCE;

SELECT 
    franchise,
    total_franchise_revenue,
    total_films,
    franchise_trajectory
FROM RPT_FRANCHISE_ANALYSIS
ORDER BY total_franchise_revenue DESC;

SELECT 
    director_name,
    films_directed,
    avg_box_office,
    avg_rt_score,
    career_span_years
FROM RPT_PEOPLE_ANALYSIS
WHERE films_directed >= 1
ORDER BY avg_box_office DESC;

SELECT 
    budget_tier,
    films_count,
    avg_roi,
    high_roi_success_rate,
    ROUND(avg_roi * (high_roi_success_rate / 100), 2) as risk_adjusted_roi
FROM RPT_BUDGET_EFFICIENCY
ORDER BY risk_adjusted_roi DESC;